name: build-and-deploy

on:
  pull_request:
    paths:
      - "data/**"
      - "Dockerfile*"
      - ".github/workflows/build-and-deploy.yaml"
  push:
    branches:
      - main
    paths:
      - "data/**"
      - "Dockerfile*"
      - ".github/workflows/build-and-deploy.yaml"
  workflow_dispatch:
    inputs:
      eclipse_version:
        description: "Eclipse version(e.g. 2021-03)"
        default: 2021-03
        required: true
      sysml_version:
        description: "SysML version(e.g. 2021-08)"
        default: 2021-08
        required: true
env:
  GHCR_TAG_BASE: ghcr.io/${{ github.repository }}
  LATEST_ECLIPSE_VERSION: 2021-09
  LATEST_SYSML_VERSION: 2022-03

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set versions for pull_request and push
        if: github.event_name != 'workflow_dispatch'
        run: |
          echo "ECLIPSE_VERSION=${{ env.LATEST_ECLIPSE_VERSION }}" >> $GITHUB_ENV
          echo "SYSML_VERSION=${{ env.LATEST_SYSML_VERSION }}" >> $GITHUB_ENV

      - name: Set versions for workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "ECLIPSE_VERSION=${{ github.event.inputs.eclipse_version }}" >> $GITHUB_ENV
          echo "SYSML_VERSION=${{ github.event.inputs.sysml_version }}" >> $GITHUB_ENV

      - name: Set image tags for pull_request and push
        if: github.event_name != 'workflow_dispatch'
        run: |
          echo "ECLIPSE_IMAGE_TAGS=${{ env.GHCR_TAG_BASE }}/eclipse:latest,${{ env.GHCR_TAG_BASE }}/eclipse:${{ env.SYSML_VERSION }}" >> $GITHUB_ENV

      - name: Set image tags for workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "ECLIPSE_IMAGE_TAGS=${{ env.GHCR_TAG_BASE }}/eclipse:${{ env.SYSML_VERSION }}" >> $GITHUB_ENV

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Packages Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.ECLIPSE_IMAGE_TAGS }}
          context: .
          file: Dockerfile.eclipse
          build-args: |
            ECLIPSE_VERSION=${{ env.ECLIPSE_VERSION }}
            SYSML_VERSION=${{ env.SYSML_VERSION }}
