name: build-and-deploy

on:
  pull_request:
    paths:
      - "data/**"
      - "Dockerfile*"
      - ".github/workflows/build-and-deploy.yaml"
  push:
    branches:
      - main
    paths:
      - "data/**"
      - "Dockerfile*"
      - ".github/workflows/build-and-deploy.yaml"
  workflow_dispatch:

env:
  GHCR_TAG_BASE: ghcr.io/${{ github.repository }}
  ECLIPSE_VERSION: 2021-03
  SYSML_VERSION: 2021-06

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run hadolint
        run: |
          brew install hadolint
          hadolint ./Dockerfile.eclipse

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Packages Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.GHCR_TAG_BASE }}/eclipse:latest
            ${{ env.GHCR_TAG_BASE }}/eclipse:${{ env.SYSML_VERSION }}
          context: .
          file: Dockerfile.eclipse
          build-args: |
            ECLIPSE_VERSION=${{ env.ECLIPSE_VERSION }}
            SYSML_VERSION=${{ env.SYSML_VERSION }}
